### ISSUE TITLE
Contact Page Still Exists

### ISSUE THREAD

**Issue by chris-hammond** [gfu-servant-engineering/tech-connect-frontend#11]
---
name: Bug report
about: Create a report to help us improve
---

# Bug report

**What is the current behavior?**
Navigating to `https://tech-connect.netlify.com/contact/` still brings up the contact page.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above.

**What is the expected behavior?**
Navigating to `https://tech-connect.netlify.com/contact/` should result in a 404.

**Other relevant information:**
Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by liliedelamotte** [comment]
After doing a little bit of digging, I'm actually a little at loss as to how to prevent that page from being accessed. There are plenty of `<Link />`s to the contact page that I don't want to remove in case we use them in the future. Do you know of a way to simply redirect the user to the 404 page if they try to access `https://tech-connect.netlify.com/contact/`?

**Comment by chris-hammond** [comment]
I'm not sure I follow. We clearly don't want anyone to follow those links... So they should either go away or later to a 404 page  In either case, can we just delete the page itself?

**Comment by liliedelamotte** [comment]
My only hesitation in deleting the contact page is that if we ever want a contact page in the future, we'll have to grab those pages from the original repo again. Am I okay to just go ahead and delete them and call it good?

**Comment by chris-hammond** [comment]
Do it! :-)

**Comment by liliedelamotte** [comment]
Cool, will do! 👍
