### ISSUE TITLE
Nav Bar on home page breaks in tablet mode

### ISSUE THREAD

**Issue by dince16** [gfu-servant-engineering/tech-connect-frontend#14]
# Bug report

**Current Behavior**
When I open the home page and shrink my browser size, I can't open the condensed menu. This is only occurring on the home page. I have been playing around with using the same navbar instance twice as header+footer in my own page and noticed this problem. *The behavior is resolved if there is only have one instance of the navbar in the .js file.*

**Steps to Reproduce**
1. Spin up frontend repo and go to the home page in localhost
2. Resize the browser window so that the menu is condensed
3. Click the menu symbol in the upper right corner and see that the condensed menu doesn't open.

**Expected Behavior**
A user should be able to see a dropdown menu appear even if the menu is condensed and the browser size is smaller. (Expected behavior occurs on the About page).

**Comment by chris-hammond** [comment]
This is fixed by pull request 24
