### ISSUE TITLE
Remove profile content type

### ISSUE THREAD

**Issue by rhill17** [gfu-servant-engineering/tech-connect-frontend#55]
Remove from gatsby_config.js
replace profile with project sponsor in queries
remove profile page template
add project sponsor field to strapi
- project sponsor name field
- project sponsor link field

**Comment by RanDumSocks** [comment]
Things left to be done as a result of the change:

- [x] Get a working build of each page
- [ ] Add sponsor section to `ProjectForm.js` and POST
  -  [ ] New field that requires the Sponsor's name.
  - Perhaps use their email as default link? In that case, change email text to something like "Sponsor's Email".
- [ ] Update `ProjectTitle.js` to reflect sponsor changes
- [ ] Update `specific-project.js` to reflect sponsor changes

Another thought that came up, should we really have a separate sponsor content type? If each project will have a 1:1 relationship with a sponsor, shouldn't we just have the sponsor be a part of the project and not separate them?
