### ISSUE TITLE
Remake Create A Project Page

### ISSUE THREAD

**Issue by dougas19** [gfu-servant-engineering/tech-connect-frontend#61]
Add profile and link to the form

**Comment by rhill17** [comment]
Currently have added project_sponsor, project_sponsor_link, and project_sponsor_image.
Still need to figure out how to get that info into the corresponding strapi content type Sponsor and then link the Project and Sponsor. I think all info would try and go into Project content type at the moment if a project was submitted.

**Comment by rhill17** [comment]
Worked on sponsor info to sponsor content type in strapi. Not sure how to test submitting a project and the info being uploaded to strapi.

**Comment by RanDumSocks** [comment]
I attached each project to the 'George Fox University' Sponsor just now. I didn't see anything pertaining to `project_sponsor`, `project_sponsor_link`, or `project_sponsor_image` in Strapi. Were you going to do that?

**Comment by rhill17** [comment]
I renamed those to just sponsor_name, sponsor_link, and sponsor_image. So those would be for the three parts of sponsor
